import { BusinessIntake } from '@/factory/schemas/intake';

const PACKAGE_DETAILS = {
  basic: {
    name: 'Starter Run',
    price: 1495,
    pages: '4-6 pages',
    timeline: '3-5 days',
    features: [
      'Gallery module',
      'Contact & lead capture',
      'SEO setup',
      'Copywriting',
      'Mobile responsive'
    ]
  },
  pro: {
    name: 'Workhorse Run',
    price: 2950,
    pages: '6-10 pages',
    timeline: '5-7 days',
    features: [
      'Everything in Starter',
      'Services database module',
      'Reviews/testimonials module',
      'Hiring page',
      'Financing page'
    ]
  },
  premium: {
    name: 'Premium Run',
    price: 6950,
    pages: '10+ pages',
    timeline: '7-10 days',
    features: [
      'Everything in Workhorse',
      'Full media kit',
      'SEO content library',
      'Hiring pipeline',
      'Brochure generation'
    ]
  }
};

export function generateProposal(intake: BusinessIntake): string {
  const pkg = PACKAGE_DETAILS[intake.packageLevel];
  
  return `# Website Factory Proposal for ${intake.businessName}

## Overview

ForgeSite Build is a website factory for builders, trades & shops. We turn your intake into a professional, lead-ready website using proven modules and automated systems.

## Business Overview
${intake.businessName} is a ${intake.tradeType} serving ${intake.serviceArea}.

## Goals
Primary goal: ${intake.mainGoal.replace('_', ' ')}
${intake.idealClientDescription ? `Target client: ${intake.idealClientDescription}` : ''}

## Recommended Factory Package: ${pkg.name}
**Investment:** $${pkg.price.toLocaleString()}
**Timeline:** Most factory runs complete in ${pkg.timeline} after intake confirmation and payment
**Pages:** ${pkg.pages}

### Included Features:
${pkg.features.map(f => `- ${f}`).join('\n')}

## Factory Run Plan

Your site will be assembled from proven modules: Hero, Services Grid, Project Gallery, Testimonials, Contact & Lead Capture.

### Recommended Pages & Modules:
- **Home:** Hero, Services Grid, Trust Bar
- **About:** Split Feature, Process Steps
- **Services:** Services Grid (detailed)
- **Projects:** Project Gallery
- **Contact:** Lead Capture, Contact Block

## Timeline

Most factory runs complete in ${pkg.timeline} after intake confirmation and payment.

## Factory Support Plan

After launch, we offer structured Factory Support Plans that include:
- Small config changes (text, images, contact info)
- Uptime monitoring
- Analytics reporting
- Form routing management

**Note:** Major layout or design changes after launch require a new factory run or upgrade, not free revisions.

## Scope Guardrails

This factory run includes the modules and pages listed above. Additional pages, major redesigns, or custom development outside our module system require a new factory run or package upgrade.

## Next Steps
1. Review and approve this proposal
2. Sign digital agreement and submit payment
3. Factory begins build (${pkg.timeline})
4. Preview site delivered for review
5. Launch and optional Factory Support Plan

## Questions?
Reply to this proposal or chat with our Factory Assistant bot for instant answers.

---
Generated by ForgeSite Build Factory System
`;
}
